map/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views

app_name = 'map'

urlpatterns = [
    url(r'^(?P<spot_id>[0-9]+)/delete$', views.delete_reservation, name='delete_reservation'),
    url(r'^(?P<spot_id>[0-9]+)/$', views.reserve, name='reserve'),
    url(r'^login$', views.login_user, name='login_user'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^$', views.map, name='index'),
]

parking/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('map.urls')),
    url(r'^map/', include('map.urls')),
]

map/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class ParkingSpot(models.Model):
    address = models.CharField(max_length=100, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lng = models.DecimalField(max_digits=9, decimal_places=6)
    is_reserved = models.BooleanField(default=False)
    reserved_until = models.DateTimeField(default=timezone.now)
    reservation_owner = models.ForeignKey('auth.User', blank=True, null=True)
    cost = models.DecimalField(max_digits=6, decimal_places=2, default=1)
    
    def clean(self):
        if self.reserved_until <= timezone.now():
            self.is_reserved = False
            self.reservation_owner = None
        else:
            self.is_reserved = True

    def __str__(self):
        return "{} {}".format(self.lat, self.lng)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=16, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

map/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import ParkingSpot, Profile

class ReservationForm(forms.ModelForm):
    # reserved_until = forms.DateTimeField(widget=forms.SplitDateTimeWidget())
    
    class Meta:
        model = ParkingSpot
        fields = ['reserved_until']
        
        
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone_number',)
        

map/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import ParkingSpot
from .forms import ReservationForm, UserForm, ProfileForm


@login_required(login_url='/login')
def map(request):

    spots = ParkingSpot.objects.all()
    
    return render(request, 'map.html', {'spots': spots})


@login_required(login_url='/login')
def reserve(request, spot_id):
    # only allow if logged in
    spot = get_object_or_404(ParkingSpot, id=spot_id)
    form = ReservationForm(request.POST or None)

    if spot.reservation_owner == request.user:
        return render(request, 'spot.html', {'form': form, 'spot': spot})

    if spot.reservation_owner != None:
        return HttpResponseRedirect('/')
    
    if form.is_valid():
        spot.reservation_owner = request.user
        spot.reserved_until = form.cleaned_data['reserved_until']
        spot.clean()
        spot.save()
        return HttpResponseRedirect('/')

    return render(request, 'spot.html', {'form': form, 'spot': spot})


@login_required(login_url='/login')
def delete_reservation(request, spot_id):
    # Delete the reservation for spot_id if it's owned by the user
    
    spot = get_object_or_404(ParkingSpot, id=spot_id)
    if spot.reservation_owner == request.user:
        spot.reservation_owner = None
        spot.reserved_until = '1994-07-13 00:00'
        spot.save()
        return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})
    return render(request, 'login.html')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')


def register(request):
    form = UserForm(request.POST)
    # profile_form = ProfileForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        # profile_form.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
    context = {
        "form": form,
        # 'profile_form': profile_form
    }
    return render(request, 'register.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Parking{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      #floating-panel {
        position: absolute;
        top: 5px;
        left: 25%;
        z-index: 5;
        background-color: #777;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto','sans-serif';
        line-height: 25px;
        padding-left: 10px;
      }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Parking</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block map_active %}{% endblock %}"><a href="/"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Map</a></li>
                <li class="{% block reservations %}{% endblock %}"><a href="/"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Reservation</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

                <li>
                    <a href="/logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Parking{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'map:index' %}">Parking</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'map:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'map:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'map:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'map:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>
</body>
</html>

templates/map.html
{% extends 'base.html' %}
{% block title %}All Spots{% endblock %}
{% block map_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

<div class=row style="height:400px;">
    <div id="floating-panel">
      <input id="address" type="textbox" value="Berkeley">
      <input id="submit" type="button" value="Center Map">
    </div>

    <div id="map"></div>
</div>

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Address</th>
                                <th>Latitude</th>
                                <th>Longitude</th>
                                <th>Reserved Until</th>
                                <th>Current Owner</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for spot in spots %}
                            
                                <tr>
                                    <td>{{ spot.address }}</td>
                                    <td>{{ spot.lat }}</td>
                                    <td>{{ spot.lng }}</td>
                                    <td><a href="{{ spot.id }}">{{ spot.reserved_until }}</a></td>
                                    <td>{{ spot.reservation_owner }}</td>
                                </tr>
                            
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
</div>



    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: {lat: 37.8719, lng: -122.2585}
        });
        
        {% for spot in spots %}
        marker = new google.maps.Marker({
              map: map,
              position: {lat: {{ spot.lat }}, lng: {{ spot.lng }}},
              label: {% if spot.reservation_owner %} 'R' {% else %} 'P' {% endif %},
              url: {{ spot.id }}
            });
        google.maps.event.addListener(marker, 'click', function() { window.location.href = this.url; });
        {% endfor %}
        var geocoder = new google.maps.Geocoder();

        document.getElementById('submit').addEventListener('click', function() {
          geocodeAddress(geocoder, map);
        });
      }

      function geocodeAddress(geocoder, resultsMap) {
        var address = document.getElementById('address').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);
            
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsdL5hFsuxorU1K3ArJcyucgAE2OHt3V0&callback=initMap">
    </script>


{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Parking{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'map:index' %}">Parking</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'map:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'map:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            {{ form.as_p }}
                            {{ profile_form.as_p }}
                            <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'map:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

</div>
</body>
</html>

templates/spot.html
{% extends 'base.html' %}
{% block title %}Reserve a spot{% endblock %}
{% block reservations %}active{% endblock %}


{% block body %}
<div class="row">
    <div class="col-sm-offset-2">
<h2>{{ spot.address }}</h2>
<h3>{{ spot }} </h3>
<h4>Cost per hour: ${{ spot.cost }}</h4>
    </div>
</div>

<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="reserve_until">Reserve until</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>

</form>
    <a href="delete" class="btn btn-danger col-sm-offset-2" role="button">Delete Reservation</a>

{% endblock %}